### ISSUE TITLE
bug searching with search areas

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-search_elastic#2]
![image](https://cloud.githubusercontent.com/assets/187449/22276758/f45a4348-e309-11e6-82ec-3748ac0f8565.png)

**Comment by brendanheywood** [comment]
Also if you set the search area to page, it shows no results, not sure if that search area filter is working at all

**Comment by mattporritt** [comment]
Yeah there are two things going on here, The stack trace is a typo. The page filter not returning results will require more investigation

**Comment by mattporritt** [comment]
https://github.com/catalyst/moodle-search_elastic/commit/820d14238a6fc69952abdc42eb49416d53722b52 fixes this issue.
Can you confirm?

**Comment by brendanheywood** [comment]
yup, error is gone. Still ignores the search area filter thought (as expected?)

**Comment by mattporritt** [comment]
Turns out there is a bit going on here. For starters the mapping for documents that was getting created was pretty broken. This meant that we weren't able to correctly filter on courses and areas.
Also the way that queries are getting constructed is incorrect.

The branch mapping contains the fix for mapping. I'm currently fixing the way search queries are constructed and will push that soon.

**Comment by mattporritt** [comment]
Current build of master should fix this

**Comment by brendanheywood** [comment]
:+1:
