### ISSUE TITLE
Any plans on supporting Elasticsearch 8.x?

### ISSUE THREAD

**Issue by pnavadia** [catalyst/moodle-search_elastic#82]
The existing code does not seem to work as-is with Elasticsearch 8.x, due to removal of types. This is causing any endpoint URL with /doc/ to return 400 - Bad Request. Also, the creation of index from the plugin fails because "doc" is no longer supported in create index BODY:

```
{
  "mappings": {
    "doc": {
      "properties": {
...
      }
    }
  }
}'
```
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html

Steps to replicate:
Install Elasticsearch 8.2. https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html
Try adding/updating index from Moodle.

**Comment by DasUberLeo** [comment]
Just your friendly neighbourhood elastic guy here. In v8.4 we also brought the Tika [Attachment Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/8.3/ingest-attachment.html) natively into the engine and made it into the [Attachment Ingestion processor](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/attachment.html).

That processor has been available for Elasticsearch since at least v5.0, and now users of v8.4 don't need to install it as a plugin. This could be a nice way to forego the need for a separate service.

**Comment by catalyst-eu** [comment]
@pnavadia Have added support for ES 8.5 in this patch - https://github.com/catalyst/moodle-search_elastic/pull/87

**Comment by jacdsouza** [comment]
@pnavadia Have added support for ES v8.5 - https://github.com/catalyst/moodle-search_elastic/issues/82

Please can you give that a try?

**Comment by michield** [comment]
I think you meant to link to #87

**Comment by jacdsouza** [comment]
ah yes, update :D

**Comment by dmitriim** [comment]
Looks like we can close this one off.
